logRetentionInDays: 14

tags:
  application: 'user-auth-api'
  environment: 'dev'

vpc:
  securityGroupIds:
    - sg-07dd5325bc2eb8150
  subnetIds:
    - subnet-0ddb85edb2198679d
    - subnet-0c24888e1258674ba
    - subnet-0bbdf08cc7a6d91ac
    - subnet-0ca1cfa21a11efeae
    - subnet-099b4dfda019d4897
    - subnet-0de799b0a2bc786d2
