logRetentionInDays: 14

tags:
  application: 'user-auth-api'
  environment: 'dev'

vpc:
  securityGroupIds:
    - sg-0f7f399e5cb0453e0
  subnetIds:
    - subnet-099d356fa7c7ef8b8
    - subnet-0d22dbfaef26cd9dd
    - subnet-0020aa0dec873b15e
    - subnet-0f1da8d626ed5a9a9
    - subnet-018859432fbabbeea
    - subnet-01fb7e02ebe5fc1f4
