logRetentionInDays: 14

tags:
  application: 'user-auth-api'
  environment: 'dev'

vpc:
  securityGroupIds:
    - sg-035e42f89debf3389
  subnetIds:
    - subnet-0d0ba40976e70d170
    - subnet-02bfb28373b33641d
    - subnet-0a2f0ad0522c01fe0
    - subnet-0e3f3290fbe08c660
    - subnet-0f29d83ecfdb030ab
    - subnet-02ad3bc77ec50f3f1
