logRetentionInDays: 14

tags:
  application: 'user-auth-api'
  environment: 'dev'

vpc:
  securityGroupIds:
    - sg-0c8a1ab73e37e9beb
  subnetIds:
    - subnet-091268709b7a7bef1
    - subnet-08b0869787a8f89be
