logRetentionInDays: 14

tags:
  application: 'user-auth-api'
  environment: 'dev'

vpc:
  securityGroupIds:
    - sg-0b1961bc0de1eb638
  subnetIds:
    - subnet-0939df42fefb5394f
    - subnet-038ed301b4b5fd944
    - subnet-0ec0d814de04650fb
    - subnet-01478c0a8f5d48fd6
    - subnet-0a09c527d086642e1
    - subnet-0e6a16f87c615c38c
