// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthParams struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type User struct {
	UserID string `json:"userID"`
	Name   string `json:"name"`
}
