name: Deploy Infrastructure

on:
  push:
    branches:
      - master

jobs:
  deploy-to-dev:
    environment: development
    name: Deploy Infrastructure to Dev
    runs-on: ubuntu-latest
    env:
      env: 'dev'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.0.0
        with:
          terragrunt_version: 0.26.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 3600

      - name: Run Terragrunt
        env:
          AWS_DEV_ACCOUNT_ID: ${{ secrets.AWS_DEV_ACCOUNT_ID }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          # make file runnable, might not be necessary
          chmod +x "${GITHUB_WORKSPACE}/.github/terragrunt.sh"

          # run script
          "${GITHUB_WORKSPACE}/.github/terragrunt.sh" ${{ env.env }}

      - name: Build
        run: make build
