name: Deploy Infrastructure

on:
  push:
    branches:
      - master

jobs:
  terragrunt:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.0.0
        with:
          terragrunt_version: 0.26.7
      - name: Interact with Terragrunt
        run: |
          terragrunt --version
          echo "Current directory: $(pwd)"
